/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.jknair.githooksteam

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'tech.jknair.githooksteam.greeting' plugin.
 */
class GitHooksTeamPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve(".githooks").mkdirs()
        projectDir.resolve(".git").mkdirs()
        projectDir.resolve(".githooks/sample").writeText("This is a sample hooks file")
        projectDir.resolve("settings.gradle.kts").writeText("")
        projectDir.resolve("build.gradle.kts").writeText("""
            plugins {
                id("java")
                id("tech.jknair.githooksteam.git-hooks-team-plugin")
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("build")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        println("------------------------------------------------------------")
        println(result.output)
        println("------------------------------------------------------------")

        // Verify the result
        assertTrue(result.output.contains("setUpGitHooks"))
    }
}
