name: CI

on:
  push:
    branches: [ master ]
  create:
    tags:
      - "^v[0-9]+$"
      - "^v[0-9]+$.[0-9]+$"
      - "^v[0-9]+$.[0-9]+$.[0-9]+$"
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle Packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ hashFiles('**/build.gradle.kts') }}
      - name: Set executable permission gradlew
        run: chmod +x ./gradlew
      - name: Run gradle checks
        run: ./gradlew check
      - name: Extract version from tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          TAGGED_VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "tag version $TAGGED_VERSION"
      - name: Publish Plugin
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: ./gradlew publishPlugins -Pversion=$TAGGED_VERSION -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
    
