# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    tags:
      - "^[0-9]+$"
      - "^[0-9]+$.[0-9]+$"
      - "^[0-9]+$.[0-9]+$.[0-9]+$"
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set executable permission gradlew
        run: chmod +x ./gradlew
      - name: Run gradle checks
        run: ./gradlew check
      - name: Extract version from tag
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/master' }}
        run: |
          TAGGED_VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "tag version $TAGGED_VERSION"
      - name: Publish Plugin
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/master' }}
        run: ./gradlew publishPlugins -Pversion=$TAGGED_VERSION -Pgradle.publish.key=${{ secrets.gradlePublishKey }} -Pgradle.publish.secret=${{ secrets.gradlePublishSecret }}
    
